experiment_name: multiclass_segmentation_no_preprocessing
seed: 42
output_base_dir: outputs

data:
  train_images_dir: "../A. Segmentation/1. Original Images/a. Training Set"
  train_hard_exudates_dir: "../A. Segmentation/2. All Segmentation Groundtruths/a. Training Set/3. Hard Exudates"
  train_haemorrhages_dir: "../A. Segmentation/2. All Segmentation Groundtruths/a. Training Set/2. Haemorrhages"
  test_images_dir: "../A. Segmentation/1. Original Images/b. Testing Set"
  test_hard_exudates_dir: "../A. Segmentation/2. All Segmentation Groundtruths/b. Testing Set/3. Hard Exudates"
  test_haemorrhages_dir: "../A. Segmentation/2. All Segmentation Groundtruths/b. Testing Set/2. Haemorrhages"

image_size: 512

model:
  name: resnet34
  encoder_weights: imagenet
  num_classes: 3

training:
  num_epochs: 100
  batch_size: 8
  num_workers: 16
  save_freq: 10

optimizer:
  name: adam
  lr: 0.0001
  weight_decay: 0.00001

scheduler:
  name: plateau
  patience: 5
  factor: 0.5

loss:
  name: combined
  alpha: 0.5

preprocessing:
  clahe: false
  center_crop: false

augmentation:
  horizontal_flip: 0.5
  vertical_flip: 0.5
  random_rotate90: 0.5
  rotation_limit: 30
  rotation_prob: 0.5
  
  brightness_contrast: 0.5
  brightness_limit: 0.3
  contrast_limit: 0.3
  hue_saturation: 0.4
  hue_shift_limit: 25
  sat_shift_limit: 40
  val_shift_limit: 25
  
  gaussian_blur: 0.2
  motion_blur: 0.2
  gaussian_noise: 0.3
  elastic_transform: 0.3
  grid_distortion: 0.2
  optical_distortion: 0.2

logging:
  use_wandb: true
  project_name: multiclass_segmentation_preprocessing_test 