data:
  segmentation:
    train_images_dir: "../A. Segmentation/1. Original Images/a. Training Set"
    train_hard_exudates_dir: "../A. Segmentation/2. All Segmentation Groundtruths/a. Training Set/3. Hard Exudates"
    train_haemorrhages_dir: "../A. Segmentation/2. All Segmentation Groundtruths/a. Training Set/2. Haemorrhages"
    test_images_dir: "../A. Segmentation/1. Original Images/b. Testing Set"
    test_hard_exudates_dir: "../A. Segmentation/2. All Segmentation Groundtruths/b. Testing Set/3. Hard Exudates"
    test_haemorrhages_dir: "../A. Segmentation/2. All Segmentation Groundtruths/b. Testing Set/2. Haemorrhages"
  
  classification:
    train_images_dir: "../B. Disease Grading/1. Original Images/a. Training Set"
    train_labels_csv: "../B. Disease Grading/2. Groundtruths/a. IDRiD_Disease Grading_Training Labels.csv"
    test_images_dir: "../B. Disease Grading/1. Original Images/b. Testing Set"
    test_labels_csv: "../B. Disease Grading/2. Groundtruths/b. IDRiD_Disease Grading_Testing Labels.csv"

model:
  backbone_name: "efficientnet_b2"
  seg_classes: 3
  cls_classes: 5
  n_experts: 8
  decoder_channels: 256

training:
  batch_size: 4
  num_epochs: 30
  learning_rate: 0.0003
  weight_decay: 0.0001
  num_workers: 4
  pin_memory: true

preprocessing:
  image_size: 512

augmentations:
  horizontal_flip_prob: 0.5
  vertical_flip_prob: 0.5
  rotate90_prob: 0.5
  brightness_contrast_prob: 0.3
  color_jitter_prob: 0.3

loss:
  alpha: 0.25
  gamma: 2.0
  smooth: 0.00001

optimizer:
  type: "AdamW"
  lr_scheduler:
    type: "ReduceLROnPlateau"
    mode: "max"
    patience: 5
    factor: 0.5

output:
  save_dir: "outputs"
  model_name: "best_mixoe_model.pth"
  plot_training_curves: true
  visualize_predictions: true
  num_visualization_samples: 2 