data:
  segmentation:
    train_images_dir: "../A. Segmentation/1. Original Images/a. Training Set"
    train_hard_exudates_dir: "../A. Segmentation/2. All Segmentation Groundtruths/a. Training Set/3. Hard Exudates"
    train_haemorrhages_dir: "../A. Segmentation/2. All Segmentation Groundtruths/a. Training Set/2. Haemorrhages"
    test_images_dir: "../A. Segmentation/1. Original Images/b. Testing Set"
    test_hard_exudates_dir: "../A. Segmentation/2. All Segmentation Groundtruths/b. Testing Set/3. Hard Exudates"
    test_haemorrhages_dir: "../A. Segmentation/2. All Segmentation Groundtruths/b. Testing Set/2. Haemorrhages"
  
  classification:
    train_images_dir: "../B. Disease Grading/1. Original Images/a. Training Set"
    train_labels_csv: "../B. Disease Grading/2. Groundtruths/a. IDRiD_Disease Grading_Training Labels.csv"
    test_images_dir: "../B. Disease Grading/1. Original Images/b. Testing Set"
    test_labels_csv: "../B. Disease Grading/2. Groundtruths/b. IDRiD_Disease Grading_Testing Labels.csv"

model:
  backbone_name: "resnext50_32x4d"
  seg_classes: 3
  cls_classes: 5
  n_experts: 8
  decoder_channels: 256
  encoder_weights: "imagenet"

training:
  batch_size: 4
  num_epochs: 50
  learning_rate: 0.0003
  weight_decay: 0.0001
  num_workers: 4
  pin_memory: true
  gradient_clip_val: 1.0

preprocessing:
  image_size: 1024
  advanced_fundus: true
  fundus_scale: 500
  clahe: false
  clahe_clip_limit: 3.0
  clahe_tile_size: 8
  center_crop: false
  crop_height: 512
  crop_width: 512

augmentations:
  # Geometric augmentations
  horizontal_flip_prob: 0.5
  vertical_flip_prob: 0.5
  rotate90_prob: 0.5
  rotation_prob: 0.3
  rotation_limit: 30
  
  # Color augmentations
  brightness_contrast_prob: 0.4
  brightness_limit: 0.3
  contrast_limit: 0.3
  hue_saturation_prob: 0.3
  hue_shift_limit: 25
  sat_shift_limit: 40
  val_shift_limit: 25
  color_jitter_prob: 0.3
  
  # Advanced augmentations
  gaussian_blur_prob: 0.2
  motion_blur_prob: 0.15
  gaussian_noise_prob: 0.2
  elastic_transform_prob: 0.1
  grid_distortion_prob: 0.1
  optical_distortion_prob: 0.1

loss:
  use_uncertainty: true
  
  # Segmentation loss
  seg_loss_name: "focal_dice_tversky"  # "dice", "focal_dice_tversky"
  focal_alpha: 1
  focal_gamma: 2
  tversky_alpha: 0.5
  tversky_beta: 0.5
  focal_weight: 0.33
  dice_weight: 0.33
  tversky_weight: 0.34
  
  # Classification loss
  cls_loss_name: "combined"  # "focal", "enhanced_focal", "combined", "label_smoothing"
  alpha: 0.25
  gamma: 2.0
  ce_weight: 0.4
  smooth_weight: 0.2
  smoothing: 0.1
  
  # Per-class alpha weights for enhanced focal loss (optional)
  alpha_weights: [1.0, 2.0, 1.5, 1.8, 2.5]  # For DR grades 0-4

optimizer:
  type: "AdamW"
  lr_scheduler:
    type: "ReduceLROnPlateau"
    mode: "max"
    patience: 7
    factor: 0.5
    min_lr: 1e-7

output:
  save_dir: "outputs"
  model_name: "best_resnext50_mixoe_model.pth"
  plot_training_curves: true
  visualize_predictions: true
  num_visualization_samples: 3
  save_detailed_report: true

wandb:
  enabled: true  # Disabled to avoid entity configuration issues
  project: "mixoe-retinal-analysis"
  name: "resnext50-combined-loss"
  tags: ["resnext50", "combined-loss", "advanced-fundus", "mixoe"]
  notes: "MixOE with ResNeXt50 backbone, combined losses, and advanced fundus preprocessing" 